# Generated by Django 6.0.3 on 2026-09-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier company or individual name', max_length=255)),
                ('contact_number', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Physical or postal address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
    ]
