# Generated by Django 6.0.3 on 2026-09-13 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand or generic name of medicine', max_length=255)),
                ('category', models.CharField(blank=True, help_text='e.g., Antibiotics, Analgesics, Antipyretics', max_length=100)),
                ('unit', models.CharField(default='tablets', help_text='Unit of measure, e.g., tablets, strips, bottles, vials, boxes', max_length=50)),
                ('manufacturer', models.CharField(blank=True, help_text='Pharmaceutical manufacturer name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Unique batch/lot identifier', max_length=100)),
                ('expiry_date', models.DateField(help_text='Expiry date for this batch')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity in this batch')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Purchase cost price per unit', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier who provided this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier')),
                ('medicine', models.ForeignKey(help_text='Associated medicine', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.medicine')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], help_text='Direction of stock movement (IN/OUT)', max_length=3)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity added or removed')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of transaction')),
                ('reason', models.TextField(blank=True, help_text='Optional reason (e.g. Purchase, Sale, Dispense, Damaged, Adjustment)', null=True)),
                ('batch', models.ForeignKey(help_text='Target batch for this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.batch')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
